config/urls.py
from django.contrib import admin
from django.urls import path, include

from graphene_django.views import GraphQLView

from .schema import schema

urlpatterns = [
    path("snippets/", include("snippets.urls", namespace="snippets")),
    path("admin/", admin.site.urls),
    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]

snippets/urls.py
from django.urls import path, include
from . import views

app_name = "snippets"
urlpatterns = [
    path("", views.SnippetListView.as_view(), name="list"),
    path("<int:pk>/", views.SnippetDetailView.as_view(), name="detail"),
]

snippets/models.py
from django.db import models


class Snippet(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def body_preview(self):
        return self.body[:50]

snippets/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Snippet
from django.views import View
from django.views.generic import ListView, DetailView


class SnippetListView(ListView):
    model = Snippet
    template_name = "snippets/snippet_list.html"


class SnippetDetailView(DetailView):
    model = Snippet
    template_name = "snippets/snippet_detail.html"

snippets/templates/snippets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
  {% block content %}

  {% endblock content %}
</body>
</html>

snippets/templates/snippets/snippet_detail.html
{% extends 'snippets/base.html' %}

{% block title %}Snippet Detail{% endblock title %}

{% block content %}

<h1>{{ snippet.title }}</h1>

<pre>
  {{ snippet.body_preview }}
</pre>

{% endblock content %}

snippets/templates/snippets/snippet_list.html
{% extends 'snippets/base.html' %}

{% block title %}Snippet List{% endblock title %}

{% block content %}

<ul>
  {% for snippet in snippet_list %}
    <li>
      <a href="{% url 'snippets:detail' snippet.id %}">{{ snippet.title }}</a>
    </li>
  {% endfor %}
</ul>

{% endblock content %}